// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: base_sdk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_base_sdk_proto protoreflect.FileDescriptor

const file_base_sdk_proto_rawDesc = "" +
	"\n" +
	"\x0ebase_sdk.proto\x12\x02pb\x1a\rrequest.proto\x1a\x0eresponse.proto2\xfa\x01\n" +
	"\x0eBaseSDKService\x12F\n" +
	"\rHasPermission\x12\x18.pb.HasPermissionRequest\x1a\x19.pb.HasPermissionResponse\"\x00\x12:\n" +
	"\tOpenOAuth\x12\x14.pb.OpenOAuthRequest\x1a\x15.pb.OpenOAuthResponse\"\x00\x12d\n" +
	"\x17VerifyApplicationSecret\x12\".pb.VerifyApplicationSecretRequest\x1a#.pb.VerifyApplicationSecretResponse\"\x00B-Z+github.com/chhongzh/chz_Base_Backend/pkg/pbb\x06proto3"

var file_base_sdk_proto_goTypes = []any{
	(*HasPermissionRequest)(nil),            // 0: pb.HasPermissionRequest
	(*OpenOAuthRequest)(nil),                // 1: pb.OpenOAuthRequest
	(*VerifyApplicationSecretRequest)(nil),  // 2: pb.VerifyApplicationSecretRequest
	(*HasPermissionResponse)(nil),           // 3: pb.HasPermissionResponse
	(*OpenOAuthResponse)(nil),               // 4: pb.OpenOAuthResponse
	(*VerifyApplicationSecretResponse)(nil), // 5: pb.VerifyApplicationSecretResponse
}
var file_base_sdk_proto_depIdxs = []int32{
	0, // 0: pb.BaseSDKService.HasPermission:input_type -> pb.HasPermissionRequest
	1, // 1: pb.BaseSDKService.OpenOAuth:input_type -> pb.OpenOAuthRequest
	2, // 2: pb.BaseSDKService.VerifyApplicationSecret:input_type -> pb.VerifyApplicationSecretRequest
	3, // 3: pb.BaseSDKService.HasPermission:output_type -> pb.HasPermissionResponse
	4, // 4: pb.BaseSDKService.OpenOAuth:output_type -> pb.OpenOAuthResponse
	5, // 5: pb.BaseSDKService.VerifyApplicationSecret:output_type -> pb.VerifyApplicationSecretResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_sdk_proto_init() }
func file_base_sdk_proto_init() {
	if File_base_sdk_proto != nil {
		return
	}
	file_request_proto_init()
	file_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_sdk_proto_rawDesc), len(file_base_sdk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_sdk_proto_goTypes,
		DependencyIndexes: file_base_sdk_proto_depIdxs,
	}.Build()
	File_base_sdk_proto = out.File
	file_base_sdk_proto_goTypes = nil
	file_base_sdk_proto_depIdxs = nil
}
