// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasPermissionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicationSecret string                 `protobuf:"bytes,1,opt,name=applicationSecret,proto3" json:"applicationSecret,omitempty"`
	AccessToken       string                 `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	PermissionKey     string                 `protobuf:"bytes,3,opt,name=permissionKey,proto3" json:"permissionKey,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HasPermissionRequest) Reset() {
	*x = HasPermissionRequest{}
	mi := &file_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionRequest) ProtoMessage() {}

func (x *HasPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionRequest.ProtoReflect.Descriptor instead.
func (*HasPermissionRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0}
}

func (x *HasPermissionRequest) GetApplicationSecret() string {
	if x != nil {
		return x.ApplicationSecret
	}
	return ""
}

func (x *HasPermissionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *HasPermissionRequest) GetPermissionKey() string {
	if x != nil {
		return x.PermissionKey
	}
	return ""
}

type OpenOAuthRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicationSecret string                 `protobuf:"bytes,1,opt,name=applicationSecret,proto3" json:"applicationSecret,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OpenOAuthRequest) Reset() {
	*x = OpenOAuthRequest{}
	mi := &file_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOAuthRequest) ProtoMessage() {}

func (x *OpenOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOAuthRequest.ProtoReflect.Descriptor instead.
func (*OpenOAuthRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{1}
}

func (x *OpenOAuthRequest) GetApplicationSecret() string {
	if x != nil {
		return x.ApplicationSecret
	}
	return ""
}

type VerifyApplicationSecretRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicationSecret string                 `protobuf:"bytes,1,opt,name=applicationSecret,proto3" json:"applicationSecret,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyApplicationSecretRequest) Reset() {
	*x = VerifyApplicationSecretRequest{}
	mi := &file_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyApplicationSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyApplicationSecretRequest) ProtoMessage() {}

func (x *VerifyApplicationSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyApplicationSecretRequest.ProtoReflect.Descriptor instead.
func (*VerifyApplicationSecretRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyApplicationSecretRequest) GetApplicationSecret() string {
	if x != nil {
		return x.ApplicationSecret
	}
	return ""
}

type CommitActionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicationSecret string                 `protobuf:"bytes,1,opt,name=applicationSecret,proto3" json:"applicationSecret,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MarshaledMeta     []byte                 `protobuf:"bytes,3,opt,name=marshaledMeta,proto3" json:"marshaledMeta,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommitActionRequest) Reset() {
	*x = CommitActionRequest{}
	mi := &file_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitActionRequest) ProtoMessage() {}

func (x *CommitActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitActionRequest.ProtoReflect.Descriptor instead.
func (*CommitActionRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{3}
}

func (x *CommitActionRequest) GetApplicationSecret() string {
	if x != nil {
		return x.ApplicationSecret
	}
	return ""
}

func (x *CommitActionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitActionRequest) GetMarshaledMeta() []byte {
	if x != nil {
		return x.MarshaledMeta
	}
	return nil
}

var File_request_proto protoreflect.FileDescriptor

const file_request_proto_rawDesc = "" +
	"\n" +
	"\rrequest.proto\x12\x02pb\"\x8c\x01\n" +
	"\x14HasPermissionRequest\x12,\n" +
	"\x11applicationSecret\x18\x01 \x01(\tR\x11applicationSecret\x12 \n" +
	"\vaccessToken\x18\x02 \x01(\tR\vaccessToken\x12$\n" +
	"\rpermissionKey\x18\x03 \x01(\tR\rpermissionKey\"@\n" +
	"\x10OpenOAuthRequest\x12,\n" +
	"\x11applicationSecret\x18\x01 \x01(\tR\x11applicationSecret\"N\n" +
	"\x1eVerifyApplicationSecretRequest\x12,\n" +
	"\x11applicationSecret\x18\x01 \x01(\tR\x11applicationSecret\"\x83\x01\n" +
	"\x13CommitActionRequest\x12,\n" +
	"\x11applicationSecret\x18\x01 \x01(\tR\x11applicationSecret\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\rmarshaledMeta\x18\x03 \x01(\fR\rmarshaledMetaB-Z+github.com/chhongzh/chz_Base_Backend/pkg/pbb\x06proto3"

var (
	file_request_proto_rawDescOnce sync.Once
	file_request_proto_rawDescData []byte
)

func file_request_proto_rawDescGZIP() []byte {
	file_request_proto_rawDescOnce.Do(func() {
		file_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)))
	})
	return file_request_proto_rawDescData
}

var file_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_request_proto_goTypes = []any{
	(*HasPermissionRequest)(nil),           // 0: pb.HasPermissionRequest
	(*OpenOAuthRequest)(nil),               // 1: pb.OpenOAuthRequest
	(*VerifyApplicationSecretRequest)(nil), // 2: pb.VerifyApplicationSecretRequest
	(*CommitActionRequest)(nil),            // 3: pb.CommitActionRequest
}
var file_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_proto_init() }
func file_request_proto_init() {
	if File_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_proto_goTypes,
		DependencyIndexes: file_request_proto_depIdxs,
		MessageInfos:      file_request_proto_msgTypes,
	}.Build()
	File_request_proto = out.File
	file_request_proto_goTypes = nil
	file_request_proto_depIdxs = nil
}
